//
// File generated by /sw//bin/rootcint at Thu Jul 21 11:38:41 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BaseSteer_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BaseSteer_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void BaseSteer_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_BaseSteer(void *p = 0);
   static void *newArray_BaseSteer(Long_t size, void *p);
   static void delete_BaseSteer(void *p);
   static void deleteArray_BaseSteer(void *p);
   static void destruct_BaseSteer(void *p);
   static void streamer_BaseSteer(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::BaseSteer*)
   {
      ::BaseSteer *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::BaseSteer >(0);
      static ::ROOT::TGenericClassInfo 
         instance("BaseSteer", ::BaseSteer::Class_Version(), "./BaseSteer.h", 12,
                  typeid(::BaseSteer), ::ROOT::DefineBehavior(ptr, ptr),
                  &::BaseSteer::Dictionary, isa_proxy, 0,
                  sizeof(::BaseSteer) );
      instance.SetNew(&new_BaseSteer);
      instance.SetNewArray(&newArray_BaseSteer);
      instance.SetDelete(&delete_BaseSteer);
      instance.SetDeleteArray(&deleteArray_BaseSteer);
      instance.SetDestructor(&destruct_BaseSteer);
      instance.SetStreamerFunc(&streamer_BaseSteer);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::BaseSteer*)
   {
      return GenerateInitInstanceLocal((::BaseSteer*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BaseSteer*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr BaseSteer::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *BaseSteer::Class_Name()
{
   return "BaseSteer";
}

//______________________________________________________________________________
const char *BaseSteer::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::BaseSteer*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int BaseSteer::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::BaseSteer*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void BaseSteer::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::BaseSteer*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *BaseSteer::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::BaseSteer*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void BaseSteer::Streamer(TBuffer &R__b)
{
   // Stream an object of class BaseSteer.

   TNamed::Streamer(R__b);
}

//______________________________________________________________________________
void BaseSteer::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class BaseSteer.
      TClass *R__cl = ::BaseSteer::IsA();
      if (R__cl || R__insp.IsA()) { }
      TNamed::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_BaseSteer(void *p) {
      return  p ? new(p) ::BaseSteer : new ::BaseSteer;
   }
   static void *newArray_BaseSteer(Long_t nElements, void *p) {
      return p ? new(p) ::BaseSteer[nElements] : new ::BaseSteer[nElements];
   }
   // Wrapper around operator delete
   static void delete_BaseSteer(void *p) {
      delete ((::BaseSteer*)p);
   }
   static void deleteArray_BaseSteer(void *p) {
      delete [] ((::BaseSteer*)p);
   }
   static void destruct_BaseSteer(void *p) {
      typedef ::BaseSteer current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_BaseSteer(TBuffer &buf, void *obj) {
      ((::BaseSteer*)obj)->::BaseSteer::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::BaseSteer

/********************************************************
* BaseSteer_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBaseSteer_Dict();

extern "C" void G__set_cpp_environmentBaseSteer_Dict() {
  G__cpp_reset_tagtableBaseSteer_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevBaseSteer_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BaseSteer */
static int G__BaseSteer_Dict_187_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BaseSteer*) G__getstructoffset())->SetValues(*(TString*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const BaseSteer*) G__getstructoffset())->SplitExpression(*(TString*) libp->para[0].ref, *(TString*) libp->para[1].ref
, *(TString*) libp->para[2].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const BaseSteer*) G__getstructoffset())->SplitString((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (TObjArray*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const BaseSteer*) G__getstructoffset())->StringToArray((const char*) G__int(libp->para[0]), *(TArrayI*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const BaseSteer*) G__getstructoffset())->StringToArray((const char*) G__int(libp->para[0]), *(TArrayD*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const BaseSteer*) G__getstructoffset())->StringToArray((const char*) G__int(libp->para[0]), *(TArrayF*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const BaseSteer*) G__getstructoffset())->PrintArray((const char*) G__int(libp->para[0]), *(TArrayI*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const BaseSteer*) G__getstructoffset())->PrintArray((const char*) G__int(libp->para[0]), *(TArrayD*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const BaseSteer*) G__getstructoffset())->PrintArray((const char*) G__int(libp->para[0]), *(TArrayF*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) BaseSteer::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BaseSteer::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) BaseSteer::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      BaseSteer::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BaseSteer*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BaseSteer::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) BaseSteer::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BaseSteer::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseSteer_Dict_187_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) BaseSteer::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic default constructor
static int G__BaseSteer_Dict_187_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BaseSteer *p;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BaseSteer[n];
     } else {
       p = new((void*) gvp) BaseSteer[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BaseSteer;
     } else {
       p = new((void*) gvp) BaseSteer;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BaseSteer_DictLN_BaseSteer));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BaseSteer_Dict_187_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BaseSteer* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BaseSteer(*(BaseSteer*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BaseSteer_DictLN_BaseSteer));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BaseSteer G__TBaseSteer;
static int G__BaseSteer_Dict_187_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BaseSteer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BaseSteer*) (soff+(sizeof(BaseSteer)*i)))->~G__TBaseSteer();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BaseSteer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BaseSteer*) (soff))->~G__TBaseSteer();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BaseSteer_Dict_187_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BaseSteer* dest = (BaseSteer*) G__getstructoffset();
   *dest = *(BaseSteer*) libp->para[0].ref;
   const BaseSteer& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BaseSteer */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBaseSteer_Dict {
 public:
  G__Sizep2memfuncBaseSteer_Dict(): p(&G__Sizep2memfuncBaseSteer_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBaseSteer_Dict::*p)();
};

size_t G__get_sizep2memfuncBaseSteer_Dict()
{
  G__Sizep2memfuncBaseSteer_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBaseSteer_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__BaseSteer_DictLN_BaseSteer))) {
     BaseSteer *G__Lderived;
     G__Lderived=(BaseSteer*)0x1000;
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BaseSteer_DictLN_BaseSteer),G__get_linked_tagnum(&G__BaseSteer_DictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BaseSteer_DictLN_BaseSteer),G__get_linked_tagnum(&G__BaseSteer_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBaseSteer_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BaseSteer_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BaseSteer_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BaseSteer_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BaseSteer_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BaseSteer_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BaseSteer_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BaseSteer_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BaseSteer_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BaseSteer_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BaseSteer_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BaseSteer */
static void G__setup_memvarBaseSteer(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BaseSteer_DictLN_BaseSteer));
   { BaseSteer *p; p=(BaseSteer*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BaseSteer_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBaseSteer_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBaseSteer(void) {
   /* BaseSteer */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BaseSteer_DictLN_BaseSteer));
   G__memfunc_setup("SetValues",924,G__BaseSteer_Dict_187_0_1, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 1 - block", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SplitExpression",1596,G__BaseSteer_Dict_187_0_2, 105, -1, G__defined_typename("Int_t"), 0, 3, 1, 1, 8, 
"u 'TString' - 11 - exp u 'TString' - 1 - left "
"u 'TString' - 1 - right", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SplitString",1155,G__BaseSteer_Dict_187_0_3, 121, -1, -1, 0, 3, 1, 1, 8, 
"C - - 10 - str C - - 10 - splitStr "
"U 'TObjArray' - 0 - result", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StringToArray",1337,G__BaseSteer_Dict_187_0_4, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 8, 
"C - - 10 - str u 'TArrayI' - 1 - result", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StringToArray",1337,G__BaseSteer_Dict_187_0_5, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 8, 
"C - - 10 - str u 'TArrayD' - 1 - result", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StringToArray",1337,G__BaseSteer_Dict_187_0_6, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 8, 
"C - - 10 - str u 'TArrayF' - 1 - result", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("PrintArray",1036,G__BaseSteer_Dict_187_0_7, 121, -1, -1, 0, 2, 1, 1, 8, 
"C - - 10 - description u 'TArrayI' - 11 - result", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("PrintArray",1036,G__BaseSteer_Dict_187_0_8, 121, -1, -1, 0, 2, 1, 1, 8, 
"C - - 10 - description u 'TArrayD' - 11 - result", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("PrintArray",1036,G__BaseSteer_Dict_187_0_9, 121, -1, -1, 0, 2, 1, 1, 8, 
"C - - 10 - description u 'TArrayF' - 11 - result", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__BaseSteer_Dict_187_0_10, 85, G__get_linked_tagnum(&G__BaseSteer_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&BaseSteer::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__BaseSteer_Dict_187_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&BaseSteer::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__BaseSteer_Dict_187_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&BaseSteer::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__BaseSteer_Dict_187_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&BaseSteer::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__BaseSteer_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__BaseSteer_Dict_187_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__BaseSteer_Dict_187_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&BaseSteer::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__BaseSteer_Dict_187_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&BaseSteer::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__BaseSteer_Dict_187_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&BaseSteer::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__BaseSteer_Dict_187_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&BaseSteer::DeclFileLine) ), 0);
   // automatic default constructor
   G__memfunc_setup("BaseSteer", 894, G__BaseSteer_Dict_187_0_22, (int) ('i'), G__get_linked_tagnum(&G__BaseSteer_DictLN_BaseSteer), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("BaseSteer", 894, G__BaseSteer_Dict_187_0_23, (int) ('i'), G__get_linked_tagnum(&G__BaseSteer_DictLN_BaseSteer), -1, 0, 1, 1, 1, 0, "u 'BaseSteer' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BaseSteer", 1020, G__BaseSteer_Dict_187_0_24, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BaseSteer_Dict_187_0_25, (int) ('u'), G__get_linked_tagnum(&G__BaseSteer_DictLN_BaseSteer), -1, 1, 1, 1, 1, 0, "u 'BaseSteer' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBaseSteer_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBaseSteer_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBaseSteer_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BaseSteer_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_TObjArray = { "TObjArray" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_TArrayI = { "TArrayI" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_TArrayD = { "TArrayD" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_TArrayF = { "TArrayF" , 99 , -1 };
G__linked_taginfo G__BaseSteer_DictLN_BaseSteer = { "BaseSteer" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBaseSteer_Dict() {
  G__BaseSteer_DictLN_TClass.tagnum = -1 ;
  G__BaseSteer_DictLN_TBuffer.tagnum = -1 ;
  G__BaseSteer_DictLN_TMemberInspector.tagnum = -1 ;
  G__BaseSteer_DictLN_TObject.tagnum = -1 ;
  G__BaseSteer_DictLN_TNamed.tagnum = -1 ;
  G__BaseSteer_DictLN_TString.tagnum = -1 ;
  G__BaseSteer_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BaseSteer_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BaseSteer_DictLN_TObjArray.tagnum = -1 ;
  G__BaseSteer_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BaseSteer_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BaseSteer_DictLN_TArrayI.tagnum = -1 ;
  G__BaseSteer_DictLN_TArrayD.tagnum = -1 ;
  G__BaseSteer_DictLN_TArrayF.tagnum = -1 ;
  G__BaseSteer_DictLN_BaseSteer.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBaseSteer_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_TString);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_TObjArray);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_TArrayI);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_TArrayD);
   G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_TArrayF);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BaseSteer_DictLN_BaseSteer),sizeof(BaseSteer),-1,61440,(char*)NULL,G__setup_memvarBaseSteer,G__setup_memfuncBaseSteer);
}
extern "C" void G__cpp_setupBaseSteer_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupBaseSteer_Dict()");
  G__set_cpp_environmentBaseSteer_Dict();
  G__cpp_setup_tagtableBaseSteer_Dict();

  G__cpp_setup_inheritanceBaseSteer_Dict();

  G__cpp_setup_typetableBaseSteer_Dict();

  G__cpp_setup_memvarBaseSteer_Dict();

  G__cpp_setup_memfuncBaseSteer_Dict();
  G__cpp_setup_globalBaseSteer_Dict();
  G__cpp_setup_funcBaseSteer_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBaseSteer_Dict();
  return;
}
class G__cpp_setup_initBaseSteer_Dict {
  public:
    G__cpp_setup_initBaseSteer_Dict() { G__add_setup_func("BaseSteer_Dict",(G__incsetup)(&G__cpp_setupBaseSteer_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBaseSteer_Dict() { G__remove_setup_func("BaseSteer_Dict"); }
};
G__cpp_setup_initBaseSteer_Dict G__cpp_setup_initializerBaseSteer_Dict;

