/********************************************************************
* BaseSteer_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BaseSteer_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBaseSteer_Dict();
extern void G__cpp_setup_inheritanceBaseSteer_Dict();
extern void G__cpp_setup_typetableBaseSteer_Dict();
extern void G__cpp_setup_memvarBaseSteer_Dict();
extern void G__cpp_setup_globalBaseSteer_Dict();
extern void G__cpp_setup_memfuncBaseSteer_Dict();
extern void G__cpp_setup_funcBaseSteer_Dict();
extern void G__set_cpp_environmentBaseSteer_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BaseSteer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BaseSteer_DictLN_TClass;
extern G__linked_taginfo G__BaseSteer_DictLN_TBuffer;
extern G__linked_taginfo G__BaseSteer_DictLN_TMemberInspector;
extern G__linked_taginfo G__BaseSteer_DictLN_TObject;
extern G__linked_taginfo G__BaseSteer_DictLN_TNamed;
extern G__linked_taginfo G__BaseSteer_DictLN_TString;
extern G__linked_taginfo G__BaseSteer_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BaseSteer_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseSteer_DictLN_TObjArray;
extern G__linked_taginfo G__BaseSteer_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BaseSteer_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaseSteer_DictLN_TArrayI;
extern G__linked_taginfo G__BaseSteer_DictLN_TArrayD;
extern G__linked_taginfo G__BaseSteer_DictLN_TArrayF;
extern G__linked_taginfo G__BaseSteer_DictLN_BaseSteer;

/* STUB derived class for protected member access */
