//
// File generated by /sw//bin/rootcint at Mon Feb 20 16:30:08 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME SHist_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "SHist_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void SHist_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_SHist(void *p);
   static void deleteArray_SHist(void *p);
   static void destruct_SHist(void *p);
   static void streamer_SHist(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::SHist*)
   {
      ::SHist *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::SHist >(0);
      static ::ROOT::TGenericClassInfo 
         instance("SHist", ::SHist::Class_Version(), "./SHist.h", 12,
                  typeid(::SHist), ::ROOT::DefineBehavior(ptr, ptr),
                  &::SHist::Dictionary, isa_proxy, 0,
                  sizeof(::SHist) );
      instance.SetDelete(&delete_SHist);
      instance.SetDeleteArray(&deleteArray_SHist);
      instance.SetDestructor(&destruct_SHist);
      instance.SetStreamerFunc(&streamer_SHist);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::SHist*)
   {
      return GenerateInitInstanceLocal((::SHist*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SHist*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr SHist::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *SHist::Class_Name()
{
   return "SHist";
}

//______________________________________________________________________________
const char *SHist::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SHist*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int SHist::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SHist*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void SHist::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SHist*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *SHist::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SHist*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void SHist::Streamer(TBuffer &R__b)
{
   // Stream an object of class SHist.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void SHist::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class SHist.
      TClass *R__cl = ::SHist::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_hist", &m_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_stack", &m_stack);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_asymme", &m_asymme);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_weight", &m_weight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_unc_arr", &m_unc_arr);
      R__insp.InspectMember(m_unc_arr, "m_unc_arr.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_process", &m_process);
      R__insp.InspectMember(m_process, "m_process.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_leg_name", &m_leg_name);
      R__insp.InspectMember(m_leg_name, "m_leg_name.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_dir", &m_dir);
      R__insp.InspectMember(m_dir, "m_dir.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_is_stack", &m_is_stack);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_is_used_in_stack", &m_is_used_in_stack);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_draw_marker", &m_draw_marker);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_draw", &m_draw);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_is_yield_plot", &m_is_yield_plot);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_draw_noxerr", &m_draw_noxerr);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_SHist(void *p) {
      delete ((::SHist*)p);
   }
   static void deleteArray_SHist(void *p) {
      delete [] ((::SHist*)p);
   }
   static void destruct_SHist(void *p) {
      typedef ::SHist current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_SHist(TBuffer &buf, void *obj) {
      ((::SHist*)obj)->::SHist::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::SHist

/********************************************************
* SHist_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableSHist_Dict();

extern "C" void G__set_cpp_environmentSHist_Dict() {
  G__cpp_reset_tagtableSHist_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevSHist_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SHist */
static int G__SHist_Dict_237_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SHist* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new SHist((TH1*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) SHist((TH1*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SHist_DictLN_SHist));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SHist* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new SHist((THStack*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) SHist((THStack*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SHist_DictLN_SHist));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->SetName(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SHist*) G__getstructoffset())->Duplicate());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->SetProcessName(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((SHist*) G__getstructoffset())->GetProcessName();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->SetLegName(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((SHist*) G__getstructoffset())->GetLegName();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->SetDir(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((SHist*) G__getstructoffset())->GetDir();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->SetIsUsedInStack((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SHist*) G__getstructoffset())->IsUsedInStack());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->SetIsStack((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SHist*) G__getstructoffset())->IsStack());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->SetIsYieldPlot((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SHist*) G__getstructoffset())->IsYieldPlot());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->SetWeight((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((SHist*) G__getstructoffset())->GetWeight());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((SHist*) G__getstructoffset())->SetUnc((double) G__double(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((SHist*) G__getstructoffset())->SetUnc((double) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((SHist*) G__getstructoffset())->GetUnc((int) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((SHist*) G__getstructoffset())->GetUnc());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->SetDoDraw((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SHist*) G__getstructoffset())->DoDraw());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->SetDrawMarker((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SHist*) G__getstructoffset())->DrawMarker());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SHist*) G__getstructoffset())->DrawLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SHist*) G__getstructoffset())->GetHist());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SHist*) G__getstructoffset())->GetStack());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((SHist*) G__getstructoffset())->GetMinimum((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((SHist*) G__getstructoffset())->GetMaximum());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->NormaliseToArea();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->DrawNoErrorX((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SHist*) G__getstructoffset())->GetNoErrorX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->SetAsymmErrors((TGraphAsymmErrors*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SHist*) G__getstructoffset())->GetAsymmErrors());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) SHist::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SHist::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) SHist::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SHist::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SHist*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SHist::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SHist::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SHist::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SHist_Dict_237_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SHist::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__SHist_Dict_237_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   SHist* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new SHist(*(SHist*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SHist_DictLN_SHist));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SHist G__TSHist;
static int G__SHist_Dict_237_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SHist*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SHist*) (soff+(sizeof(SHist)*i)))->~G__TSHist();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SHist*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SHist*) (soff))->~G__TSHist();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__SHist_Dict_237_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SHist* dest = (SHist*) G__getstructoffset();
   *dest = *(SHist*) libp->para[0].ref;
   const SHist& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SHist */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncSHist_Dict {
 public:
  G__Sizep2memfuncSHist_Dict(): p(&G__Sizep2memfuncSHist_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncSHist_Dict::*p)();
};

size_t G__get_sizep2memfuncSHist_Dict()
{
  G__Sizep2memfuncSHist_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceSHist_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__SHist_DictLN_SHist))) {
     SHist *G__Lderived;
     G__Lderived=(SHist*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SHist_DictLN_SHist),G__get_linked_tagnum(&G__SHist_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableSHist_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SHist_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SHist_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SHist_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SHist_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SHist_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SHist_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SHist_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SHist_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SHist_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SHist_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__SHist_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__SHist_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SHist_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SHist_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__SHist_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__SHist_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__SHist_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__SHist_DictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__SHist_DictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SHist */
static void G__setup_memvarSHist(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SHist_DictLN_SHist));
   { SHist *p; p=(SHist*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SHist_DictLN_TH1),-1,-1,4,"m_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SHist_DictLN_THStack),-1,-1,4,"m_stack=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SHist_DictLN_TGraphAsymmErrors),-1,-1,4,"m_asymme=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_weight=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SHist_DictLN_TArrayD),-1,-1,4,"m_unc_arr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SHist_DictLN_TString),-1,-1,4,"m_process=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SHist_DictLN_TString),-1,-1,4,"m_leg_name=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SHist_DictLN_TString),-1,-1,4,"m_dir=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_is_stack=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_is_used_in_stack=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_draw_marker=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_draw=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_is_yield_plot=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_draw_noxerr=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SHist_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarSHist_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSHist(void) {
   /* SHist */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SHist_DictLN_SHist));
   G__memfunc_setup("SHist",491,G__SHist_Dict_237_0_1, 105, G__get_linked_tagnum(&G__SHist_DictLN_SHist), -1, 0, 1, 1, 1, 0, "U 'TH1' - 0 - hist", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SHist",491,G__SHist_Dict_237_0_2, 105, G__get_linked_tagnum(&G__SHist_DictLN_SHist), -1, 0, 1, 1, 1, 0, "U 'THStack' - 0 - stack", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetName",673,(G__InterfaceMethod) NULL,67, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetName",685,G__SHist_Dict_237_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Duplicate",923,G__SHist_Dict_237_0_5, 85, G__get_linked_tagnum(&G__SHist_DictLN_SHist), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetProcessName",1420,G__SHist_Dict_237_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetProcessName",1408,G__SHist_Dict_237_0_7, 117, G__get_linked_tagnum(&G__SHist_DictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetLegName",965,G__SHist_Dict_237_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLegName",953,G__SHist_Dict_237_0_9, 117, G__get_linked_tagnum(&G__SHist_DictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDir",587,G__SHist_Dict_237_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDir",575,G__SHist_Dict_237_0_11, 117, G__get_linked_tagnum(&G__SHist_DictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetIsUsedInStack",1574,G__SHist_Dict_237_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsUsedInStack",1274,G__SHist_Dict_237_0_13, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetIsStack",990,G__SHist_Dict_237_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsStack",690,G__SHist_Dict_237_0_15, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetIsYieldPlot",1406,G__SHist_Dict_237_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsYieldPlot",1106,G__SHist_Dict_237_0_17, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetWeight",916,G__SHist_Dict_237_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWeight",904,G__SHist_Dict_237_0_19, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetUnc",594,G__SHist_Dict_237_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - unc i - - 0 '0' i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetUnc",582,G__SHist_Dict_237_0_21, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 '0' i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDoDraw",877,G__SHist_Dict_237_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoDraw",577,G__SHist_Dict_237_0_23, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDrawMarker",1308,G__SHist_Dict_237_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawMarker",1008,G__SHist_Dict_237_0_25, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawLine",790,G__SHist_Dict_237_0_26, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHist",696,G__SHist_Dict_237_0_27, 85, G__get_linked_tagnum(&G__SHist_DictLN_TH1), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetStack",790,G__SHist_Dict_237_0_28, 85, G__get_linked_tagnum(&G__SHist_DictLN_THStack), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMinimum",1020,G__SHist_Dict_237_0_29, 100, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - minval", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMaximum",1022,G__SHist_Dict_237_0_30, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NormaliseToArea",1510,G__SHist_Dict_237_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawNoErrorX",1197,G__SHist_Dict_237_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNoErrorX",1087,G__SHist_Dict_237_0_33, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Draw",398,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetAsymmErrors",1456,G__SHist_Dict_237_0_35, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TGraphAsymmErrors' - 0 - as", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetAsymmErrors",1444,G__SHist_Dict_237_0_36, 85, G__get_linked_tagnum(&G__SHist_DictLN_TGraphAsymmErrors), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__SHist_Dict_237_0_37, 85, G__get_linked_tagnum(&G__SHist_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&SHist::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__SHist_Dict_237_0_38, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SHist::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__SHist_Dict_237_0_39, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&SHist::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__SHist_Dict_237_0_40, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&SHist::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__SHist_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__SHist_Dict_237_0_44, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__SHist_Dict_237_0_45, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SHist::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__SHist_Dict_237_0_46, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SHist::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__SHist_Dict_237_0_47, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SHist::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__SHist_Dict_237_0_48, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SHist::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("SHist", 491, G__SHist_Dict_237_0_49, (int) ('i'), G__get_linked_tagnum(&G__SHist_DictLN_SHist), -1, 0, 1, 1, 1, 0, "u 'SHist' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~SHist", 617, G__SHist_Dict_237_0_50, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__SHist_Dict_237_0_51, (int) ('u'), G__get_linked_tagnum(&G__SHist_DictLN_SHist), -1, 1, 1, 1, 1, 0, "u 'SHist' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncSHist_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalSHist_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcSHist_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__SHist_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_TArrayD = { "TArrayD" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__SHist_DictLN_THStack = { "THStack" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_TGraphAsymmErrors = { "TGraphAsymmErrors" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__SHist_DictLN_SHist = { "SHist" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableSHist_Dict() {
  G__SHist_DictLN_TClass.tagnum = -1 ;
  G__SHist_DictLN_TBuffer.tagnum = -1 ;
  G__SHist_DictLN_TMemberInspector.tagnum = -1 ;
  G__SHist_DictLN_TObject.tagnum = -1 ;
  G__SHist_DictLN_TString.tagnum = -1 ;
  G__SHist_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__SHist_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SHist_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__SHist_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SHist_DictLN_TArrayD.tagnum = -1 ;
  G__SHist_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__SHist_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__SHist_DictLN_TH1.tagnum = -1 ;
  G__SHist_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__SHist_DictLN_THStack.tagnum = -1 ;
  G__SHist_DictLN_TGraphAsymmErrors.tagnum = -1 ;
  G__SHist_DictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__SHist_DictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__SHist_DictLN_SHist.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableSHist_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_TString);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_TArrayD);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_TH1);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_THStack);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_TGraphAsymmErrors);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__SHist_DictLN_TMatrixTBaselEdoublegR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SHist_DictLN_SHist),sizeof(SHist),-1,62464,"SFrame histograms",G__setup_memvarSHist,G__setup_memfuncSHist);
}
extern "C" void G__cpp_setupSHist_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupSHist_Dict()");
  G__set_cpp_environmentSHist_Dict();
  G__cpp_setup_tagtableSHist_Dict();

  G__cpp_setup_inheritanceSHist_Dict();

  G__cpp_setup_typetableSHist_Dict();

  G__cpp_setup_memvarSHist_Dict();

  G__cpp_setup_memfuncSHist_Dict();
  G__cpp_setup_globalSHist_Dict();
  G__cpp_setup_funcSHist_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncSHist_Dict();
  return;
}
class G__cpp_setup_initSHist_Dict {
  public:
    G__cpp_setup_initSHist_Dict() { G__add_setup_func("SHist_Dict",(G__incsetup)(&G__cpp_setupSHist_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initSHist_Dict() { G__remove_setup_func("SHist_Dict"); }
};
G__cpp_setup_initSHist_Dict G__cpp_setup_initializerSHist_Dict;

