/********************************************************************
* SHist_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SHist_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSHist_Dict();
extern void G__cpp_setup_inheritanceSHist_Dict();
extern void G__cpp_setup_typetableSHist_Dict();
extern void G__cpp_setup_memvarSHist_Dict();
extern void G__cpp_setup_globalSHist_Dict();
extern void G__cpp_setup_memfuncSHist_Dict();
extern void G__cpp_setup_funcSHist_Dict();
extern void G__set_cpp_environmentSHist_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SHist.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SHist_DictLN_TClass;
extern G__linked_taginfo G__SHist_DictLN_TBuffer;
extern G__linked_taginfo G__SHist_DictLN_TMemberInspector;
extern G__linked_taginfo G__SHist_DictLN_TObject;
extern G__linked_taginfo G__SHist_DictLN_TString;
extern G__linked_taginfo G__SHist_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SHist_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SHist_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SHist_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SHist_DictLN_TArrayD;
extern G__linked_taginfo G__SHist_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SHist_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SHist_DictLN_TH1;
extern G__linked_taginfo G__SHist_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SHist_DictLN_THStack;
extern G__linked_taginfo G__SHist_DictLN_TGraphAsymmErrors;
extern G__linked_taginfo G__SHist_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SHist_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SHist_DictLN_SHist;

/* STUB derived class for protected member access */
