/********************************************************************
* SteerPlotter_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SteerPlotter_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSteerPlotter_Dict();
extern void G__cpp_setup_inheritanceSteerPlotter_Dict();
extern void G__cpp_setup_typetableSteerPlotter_Dict();
extern void G__cpp_setup_memvarSteerPlotter_Dict();
extern void G__cpp_setup_globalSteerPlotter_Dict();
extern void G__cpp_setup_memfuncSteerPlotter_Dict();
extern void G__cpp_setup_funcSteerPlotter_Dict();
extern void G__set_cpp_environmentSteerPlotter_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SteerPlotter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SteerPlotter_DictLN_TClass;
extern G__linked_taginfo G__SteerPlotter_DictLN_TBuffer;
extern G__linked_taginfo G__SteerPlotter_DictLN_TMemberInspector;
extern G__linked_taginfo G__SteerPlotter_DictLN_TObject;
extern G__linked_taginfo G__SteerPlotter_DictLN_TNamed;
extern G__linked_taginfo G__SteerPlotter_DictLN_TString;
extern G__linked_taginfo G__SteerPlotter_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SteerPlotter_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SteerPlotter_DictLN_TObjArray;
extern G__linked_taginfo G__SteerPlotter_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SteerPlotter_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SteerPlotter_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SteerPlotter_DictLN_TArrayI;
extern G__linked_taginfo G__SteerPlotter_DictLN_TArrayF;
extern G__linked_taginfo G__SteerPlotter_DictLN_BaseSteer;
extern G__linked_taginfo G__SteerPlotter_DictLN_SteerPlotter;

/* STUB derived class for protected member access */
