//
// File generated by /sw//bin/rootcint at Thu Jul 21 11:38:40 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME SteerPlotter_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "SteerPlotter_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void SteerPlotter_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_SteerPlotter(void *p = 0);
   static void *newArray_SteerPlotter(Long_t size, void *p);
   static void delete_SteerPlotter(void *p);
   static void deleteArray_SteerPlotter(void *p);
   static void destruct_SteerPlotter(void *p);
   static void streamer_SteerPlotter(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::SteerPlotter*)
   {
      ::SteerPlotter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::SteerPlotter >(0);
      static ::ROOT::TGenericClassInfo 
         instance("SteerPlotter", ::SteerPlotter::Class_Version(), "./SteerPlotter.h", 11,
                  typeid(::SteerPlotter), ::ROOT::DefineBehavior(ptr, ptr),
                  &::SteerPlotter::Dictionary, isa_proxy, 0,
                  sizeof(::SteerPlotter) );
      instance.SetNew(&new_SteerPlotter);
      instance.SetNewArray(&newArray_SteerPlotter);
      instance.SetDelete(&delete_SteerPlotter);
      instance.SetDeleteArray(&deleteArray_SteerPlotter);
      instance.SetDestructor(&destruct_SteerPlotter);
      instance.SetStreamerFunc(&streamer_SteerPlotter);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::SteerPlotter*)
   {
      return GenerateInitInstanceLocal((::SteerPlotter*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SteerPlotter*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr SteerPlotter::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *SteerPlotter::Class_Name()
{
   return "SteerPlotter";
}

//______________________________________________________________________________
const char *SteerPlotter::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SteerPlotter*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int SteerPlotter::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SteerPlotter*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void SteerPlotter::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SteerPlotter*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *SteerPlotter::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SteerPlotter*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void SteerPlotter::Streamer(TBuffer &R__b)
{
   // Stream an object of class SteerPlotter.

   BaseSteer::Streamer(R__b);
}

//______________________________________________________________________________
void SteerPlotter::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class SteerPlotter.
      TClass *R__cl = ::SteerPlotter::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bShapeNorm", &bShapeNorm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bLumiNorm", &bLumiNorm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bRatioPlot", &bRatioPlot);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bZScoreInRatio", &bZScoreInRatio);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bLogy", &bLogy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bPortrait", &bPortrait);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bDrawEntries", &bDrawEntries);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bDrawLumi", &bDrawLumi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bForPrelim", &bForPrelim);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bForPublication", &bForPublication);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bDrawLegend", &bDrawLegend);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bFitPtBalanceHists", &bFitPtBalanceHists);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bJetShapesPerSlice", &bJetShapesPerSlice);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bDoCumulative", &bDoCumulative);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bSingleEPS", &bSingleEPS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bPlotThetaFile", &bPlotThetaFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bIgnoreEmptyBins", &bIgnoreEmptyBins);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNumOfSamples", &fNumOfSamples);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fLumi", &fLumi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSysError", &fSysError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSampleNames", &fSampleNames);
      R__insp.InspectMember(fSampleNames, "fSampleNames.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSamplesToStack", &fSamplesToStack);
      R__insp.InspectMember(fSamplesToStack, "fSamplesToStack.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNumOfSamplesToStack", &fNumOfSamplesToStack);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bSubstractBkgd", &bSubstractBkgd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSamplesWeight", &fSamplesWeight);
      R__insp.InspectMember(fSamplesWeight, "fSamplesWeight.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSamplesUnc", &fSamplesUnc);
      R__insp.InspectMember(fSamplesUnc, "fSamplesUnc.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fInputFiles", &fInputFiles);
      R__insp.InspectMember(fInputFiles, "fInputFiles.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCycleName", &fCycleName);
      R__insp.InspectMember(fCycleName, "fCycleName.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fOutputPsFile", &fOutputPsFile);
      R__insp.InspectMember(fOutputPsFile, "fOutputPsFile.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fHistColors", &fHistColors);
      R__insp.InspectMember(fHistColors, "fHistColors.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fHistMarkers", &fHistMarkers);
      R__insp.InspectMember(fHistMarkers, "fHistMarkers.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fLegStrings", &fLegStrings);
      R__insp.InspectMember(fLegStrings, "fLegStrings.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fScaleSysUnc", &fScaleSysUnc);
      R__insp.InspectMember(fScaleSysUnc, "fScaleSysUnc.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSysUncWeight", &fSysUncWeight);
      R__insp.InspectMember(fSysUncWeight, "fSysUncWeight.");
      BaseSteer::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_SteerPlotter(void *p) {
      return  p ? new(p) ::SteerPlotter : new ::SteerPlotter;
   }
   static void *newArray_SteerPlotter(Long_t nElements, void *p) {
      return p ? new(p) ::SteerPlotter[nElements] : new ::SteerPlotter[nElements];
   }
   // Wrapper around operator delete
   static void delete_SteerPlotter(void *p) {
      delete ((::SteerPlotter*)p);
   }
   static void deleteArray_SteerPlotter(void *p) {
      delete [] ((::SteerPlotter*)p);
   }
   static void destruct_SteerPlotter(void *p) {
      typedef ::SteerPlotter current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_SteerPlotter(TBuffer &buf, void *obj) {
      ((::SteerPlotter*)obj)->::SteerPlotter::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::SteerPlotter

/********************************************************
* SteerPlotter_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableSteerPlotter_Dict();

extern "C" void G__set_cpp_environmentSteerPlotter_Dict() {
  G__cpp_reset_tagtableSteerPlotter_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevSteerPlotter_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SteerPlotter */
static int G__SteerPlotter_Dict_196_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SteerPlotter* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SteerPlotter[n];
     } else {
       p = new((void*) gvp) SteerPlotter[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SteerPlotter;
     } else {
       p = new((void*) gvp) SteerPlotter;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SteerPlotter_DictLN_SteerPlotter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetShapeNorm((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetShapeNorm());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetLumiNorm((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetLumiNorm());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetRatioPlot((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetRatioPlot());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetZScoreInRatio((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetZScoreInRatio());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetPortrait((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetPortrait());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetFitPtBalanceHists((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetFitPtBalanceHists());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetJetShapesPerSlice((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetJetShapesPerSlice());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetDrawEntries((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetDrawEntries());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetSampleNames((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SteerPlotter*) G__getstructoffset())->GetSampleNames());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetInputFiles((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SteerPlotter*) G__getstructoffset())->GetInputFiles());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetOutputPsFile((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((SteerPlotter*) G__getstructoffset())->GetOutputPsFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetCycleName((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((SteerPlotter*) G__getstructoffset())->GetCycleName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetLegStrings((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SteerPlotter*) G__getstructoffset())->GetLegStrings());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetScaleSysUnc((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SteerPlotter*) G__getstructoffset())->GetScaleSysUnc());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetSysUncWeight((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TArrayF* pobj;
         TArrayF xobj = ((SteerPlotter*) G__getstructoffset())->GetSysUncWeight();
         pobj = new TArrayF(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetHistColors((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TArrayI* pobj;
         TArrayI xobj = ((SteerPlotter*) G__getstructoffset())->GetHistColors();
         pobj = new TArrayI(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetHistMarkers((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TArrayI* pobj;
         TArrayI xobj = ((SteerPlotter*) G__getstructoffset())->GetHistMarkers();
         pobj = new TArrayI(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetSamplesToStack((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SteerPlotter*) G__getstructoffset())->GetSamplesToStack());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetSamplesWeight((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TArrayF* pobj;
         TArrayF xobj = ((SteerPlotter*) G__getstructoffset())->GetSamplesWeight();
         pobj = new TArrayF(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetSamplesUnc((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TArrayF* pobj;
         TArrayF xobj = ((SteerPlotter*) G__getstructoffset())->GetSamplesUnc();
         pobj = new TArrayF(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetSubstractBkgd((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetSubstractBkgd());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetDrawLumi((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetDrawLumi());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetForPrelim((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetForPrelim());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetForPublication((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetForPublication());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetDrawLegend((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetDrawLegend());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetLumi((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((SteerPlotter*) G__getstructoffset())->GetLumi());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetSysError((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((SteerPlotter*) G__getstructoffset())->GetSysError());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetDoCumulative((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetDoCumulative());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetSingleEPS((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_60(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetSingleEPS());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetIgnoreEmptyBins((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetIgnoreEmptyBins());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetPlotThetaFile((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetPlotThetaFile());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->SetLogy((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SteerPlotter*) G__getstructoffset())->GetLogy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) SteerPlotter::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SteerPlotter::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_69(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) SteerPlotter::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_70(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SteerPlotter::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_74(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SteerPlotter*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_75(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SteerPlotter::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_76(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SteerPlotter::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_77(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SteerPlotter::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SteerPlotter_Dict_196_0_78(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SteerPlotter::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SteerPlotter G__TSteerPlotter;
static int G__SteerPlotter_Dict_196_0_79(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SteerPlotter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SteerPlotter*) (soff+(sizeof(SteerPlotter)*i)))->~G__TSteerPlotter();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SteerPlotter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SteerPlotter*) (soff))->~G__TSteerPlotter();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SteerPlotter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncSteerPlotter_Dict {
 public:
  G__Sizep2memfuncSteerPlotter_Dict(): p(&G__Sizep2memfuncSteerPlotter_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncSteerPlotter_Dict::*p)();
};

size_t G__get_sizep2memfuncSteerPlotter_Dict()
{
  G__Sizep2memfuncSteerPlotter_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceSteerPlotter_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__SteerPlotter_DictLN_SteerPlotter))) {
     SteerPlotter *G__Lderived;
     G__Lderived=(SteerPlotter*)0x1000;
     {
       BaseSteer *G__Lpbase=(BaseSteer*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SteerPlotter_DictLN_SteerPlotter),G__get_linked_tagnum(&G__SteerPlotter_DictLN_BaseSteer),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SteerPlotter_DictLN_SteerPlotter),G__get_linked_tagnum(&G__SteerPlotter_DictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SteerPlotter_DictLN_SteerPlotter),G__get_linked_tagnum(&G__SteerPlotter_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableSteerPlotter_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SteerPlotter_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SteerPlotter_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SteerPlotter_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SteerPlotter_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SteerPlotter_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SteerPlotter_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SteerPlotter_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SteerPlotter_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__SteerPlotter_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__SteerPlotter_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__SteerPlotter_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SteerPlotter */
static void G__setup_memvarSteerPlotter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SteerPlotter_DictLN_SteerPlotter));
   { SteerPlotter *p; p=(SteerPlotter*)0x1000; if (p) { }
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bShapeNorm=",0,"Shape normalization?");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bLumiNorm=",0,"Lumi normalization?");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bRatioPlot=",0,"plot ratios");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bZScoreInRatio=",0,"plot z-score instead of usual ratio");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bLogy=",0,"plot y-axis on log scale?");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bPortrait=",0,"portrait or landscape ");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bDrawEntries=",0,"draw the number of entries?");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bDrawLumi=",0,"draw the lumi information?");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bForPrelim=",0,"write \"CMS Preliminary\"");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bForPublication=",0,"write \"CMS\"");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bDrawLegend=",0,"draw the legend everywhere?");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bFitPtBalanceHists=",0,"fit Pt-balance histograms?");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bJetShapesPerSlice=",0,"plot each slide of the jet shape histograms?");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bDoCumulative=",0,"do cumulative distributions instead of normal plots");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bSingleEPS=",0,"make one EPS file for each histogram");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bPlotThetaFile=",0,"take input histograms from theta file");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bIgnoreEmptyBins=",0,"ignore empty bins in the ratio");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNumOfSamples=",0,"how many analysis samples should be plotted");
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fLumi=",0,"integrated luminosity of sample");
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fSysError=",0,"systematic error on normalisation");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TObjArray),-1,-1,4,"fSampleNames=",0,"all sample name");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TObjArray),-1,-1,4,"fSamplesToStack=",0,"name of samples that should be stacked on top of each other");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNumOfSamplesToStack=",0,"how many samples should be stacked");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"bSubstractBkgd=",0,"substract all background samples?");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TArrayF),-1,-1,4,"fSamplesWeight=",0,"weights for the different samples");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TArrayF),-1,-1,4,"fSamplesUnc=",0,"uncertainty on the normalisation of various samples");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TObjArray),-1,-1,4,"fInputFiles=",0,"input filenames");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TString),-1,-1,4,"fCycleName=",0,"name of the cycle, can be used as prefix for the filenames");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TString),-1,-1,4,"fOutputPsFile=",0,"name of the resulting ps file");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TArrayI),-1,-1,4,"fHistColors=",0,"the histogram colors");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TArrayI),-1,-1,4,"fHistMarkers=",0,"the histogram markers");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TObjArray),-1,-1,4,"fLegStrings=",0,"legend entries");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TObjArray),-1,-1,4,"fScaleSysUnc=",0,"names of systematic uncertainties to scale ");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TArrayF),-1,-1,4,"fSysUncWeight=",0,"scaling factor for systematic uncertainties");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SteerPlotter_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarSteerPlotter_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSteerPlotter(void) {
   /* SteerPlotter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SteerPlotter_DictLN_SteerPlotter));
   G__memfunc_setup("SteerPlotter",1261,G__SteerPlotter_Dict_196_0_1, 105, G__get_linked_tagnum(&G__SteerPlotter_DictLN_SteerPlotter), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 8, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetShapeNorm",1209,G__SteerPlotter_Dict_196_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetShapeNorm",1197,G__SteerPlotter_Dict_196_0_4, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetLumiNorm",1119,G__SteerPlotter_Dict_196_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLumiNorm",1107,G__SteerPlotter_Dict_196_0_6, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetRatioPlot",1226,G__SteerPlotter_Dict_196_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRatioPlot",1214,G__SteerPlotter_Dict_196_0_8, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetZScoreInRatio",1592,G__SteerPlotter_Dict_196_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetZScoreInRatio",1580,G__SteerPlotter_Dict_196_0_10, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPortrait",1153,G__SteerPlotter_Dict_196_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPortrait",1141,G__SteerPlotter_Dict_196_0_12, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFitPtBalanceHists",1988,G__SteerPlotter_Dict_196_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFitPtBalanceHists",1976,G__SteerPlotter_Dict_196_0_14, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetJetShapesPerSlice",1994,G__SteerPlotter_Dict_196_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetJetShapesPerSlice",1982,G__SteerPlotter_Dict_196_0_16, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDrawEntries",1428,G__SteerPlotter_Dict_196_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDrawEntries",1416,G__SteerPlotter_Dict_196_0_18, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSampleNames",1410,G__SteerPlotter_Dict_196_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSampleNames",1398,G__SteerPlotter_Dict_196_0_20, 85, G__get_linked_tagnum(&G__SteerPlotter_DictLN_TObjArray), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetInputFiles",1327,G__SteerPlotter_Dict_196_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetInputFiles",1315,G__SteerPlotter_Dict_196_0_22, 85, G__get_linked_tagnum(&G__SteerPlotter_DictLN_TObjArray), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetOutputPsFile",1536,G__SteerPlotter_Dict_196_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetOutputPsFile",1524,G__SteerPlotter_Dict_196_0_24, 67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCycleName",1181,G__SteerPlotter_Dict_196_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCycleName",1169,G__SteerPlotter_Dict_196_0_26, 67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetLegStrings",1326,G__SteerPlotter_Dict_196_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLegStrings",1314,G__SteerPlotter_Dict_196_0_28, 85, G__get_linked_tagnum(&G__SteerPlotter_DictLN_TObjArray), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetScaleSysUnc",1401,G__SteerPlotter_Dict_196_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetScaleSysUnc",1389,G__SteerPlotter_Dict_196_0_30, 85, G__get_linked_tagnum(&G__SteerPlotter_DictLN_TObjArray), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSysUncWeight",1529,G__SteerPlotter_Dict_196_0_31, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSysUncWeight",1517,G__SteerPlotter_Dict_196_0_32, 117, G__get_linked_tagnum(&G__SteerPlotter_DictLN_TArrayF), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHistColors",1334,G__SteerPlotter_Dict_196_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHistColors",1322,G__SteerPlotter_Dict_196_0_34, 117, G__get_linked_tagnum(&G__SteerPlotter_DictLN_TArrayI), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHistMarkers",1433,G__SteerPlotter_Dict_196_0_35, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHistMarkers",1421,G__SteerPlotter_Dict_196_0_36, 117, G__get_linked_tagnum(&G__SteerPlotter_DictLN_TArrayI), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSamplesToStack",1722,G__SteerPlotter_Dict_196_0_37, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSamplesToStack",1710,G__SteerPlotter_Dict_196_0_38, 85, G__get_linked_tagnum(&G__SteerPlotter_DictLN_TObjArray), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSamplesWeight",1641,G__SteerPlotter_Dict_196_0_39, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSamplesWeight",1629,G__SteerPlotter_Dict_196_0_40, 117, G__get_linked_tagnum(&G__SteerPlotter_DictLN_TArrayF), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSamplesUnc",1319,G__SteerPlotter_Dict_196_0_41, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - in", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSamplesUnc",1307,G__SteerPlotter_Dict_196_0_42, 117, G__get_linked_tagnum(&G__SteerPlotter_DictLN_TArrayF), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSubstractBkgd",1631,G__SteerPlotter_Dict_196_0_43, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSubstractBkgd",1619,G__SteerPlotter_Dict_196_0_44, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDrawLumi",1105,G__SteerPlotter_Dict_196_0_45, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDrawLumi",1093,G__SteerPlotter_Dict_196_0_46, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetForPrelim",1212,G__SteerPlotter_Dict_196_0_47, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetForPrelim",1200,G__SteerPlotter_Dict_196_0_48, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetForPublication",1741,G__SteerPlotter_Dict_196_0_49, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetForPublication",1729,G__SteerPlotter_Dict_196_0_50, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDrawLegend",1289,G__SteerPlotter_Dict_196_0_51, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDrawLegend",1277,G__SteerPlotter_Dict_196_0_52, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetLumi",707,G__SteerPlotter_Dict_196_0_53, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - lumi", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLumi",695,G__SteerPlotter_Dict_196_0_54, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSysError",1141,G__SteerPlotter_Dict_196_0_55, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - err", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSysError",1129,G__SteerPlotter_Dict_196_0_56, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDoCumulative",1534,G__SteerPlotter_Dict_196_0_57, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDoCumulative",1522,G__SteerPlotter_Dict_196_0_58, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSingleEPS",1142,G__SteerPlotter_Dict_196_0_59, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSingleEPS",1130,G__SteerPlotter_Dict_196_0_60, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetIgnoreEmptyBins",1835,G__SteerPlotter_Dict_196_0_61, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIgnoreEmptyBins",1823,G__SteerPlotter_Dict_196_0_62, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPlotThetaFile",1601,G__SteerPlotter_Dict_196_0_63, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPlotThetaFile",1589,G__SteerPlotter_Dict_196_0_64, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetLogy",711,G__SteerPlotter_Dict_196_0_65, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLogy",699,G__SteerPlotter_Dict_196_0_66, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__SteerPlotter_Dict_196_0_67, 85, G__get_linked_tagnum(&G__SteerPlotter_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&SteerPlotter::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__SteerPlotter_Dict_196_0_68, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SteerPlotter::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__SteerPlotter_Dict_196_0_69, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&SteerPlotter::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__SteerPlotter_Dict_196_0_70, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&SteerPlotter::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__SteerPlotter_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__SteerPlotter_Dict_196_0_74, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__SteerPlotter_Dict_196_0_75, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SteerPlotter::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__SteerPlotter_Dict_196_0_76, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SteerPlotter::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__SteerPlotter_Dict_196_0_77, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SteerPlotter::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__SteerPlotter_Dict_196_0_78, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SteerPlotter::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~SteerPlotter", 1387, G__SteerPlotter_Dict_196_0_79, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncSteerPlotter_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalSteerPlotter_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcSteerPlotter_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__SteerPlotter_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_TObjArray = { "TObjArray" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_TArrayI = { "TArrayI" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_TArrayF = { "TArrayF" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_BaseSteer = { "BaseSteer" , 99 , -1 };
G__linked_taginfo G__SteerPlotter_DictLN_SteerPlotter = { "SteerPlotter" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableSteerPlotter_Dict() {
  G__SteerPlotter_DictLN_TClass.tagnum = -1 ;
  G__SteerPlotter_DictLN_TBuffer.tagnum = -1 ;
  G__SteerPlotter_DictLN_TMemberInspector.tagnum = -1 ;
  G__SteerPlotter_DictLN_TObject.tagnum = -1 ;
  G__SteerPlotter_DictLN_TNamed.tagnum = -1 ;
  G__SteerPlotter_DictLN_TString.tagnum = -1 ;
  G__SteerPlotter_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__SteerPlotter_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SteerPlotter_DictLN_TObjArray.tagnum = -1 ;
  G__SteerPlotter_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__SteerPlotter_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SteerPlotter_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__SteerPlotter_DictLN_TArrayI.tagnum = -1 ;
  G__SteerPlotter_DictLN_TArrayF.tagnum = -1 ;
  G__SteerPlotter_DictLN_BaseSteer.tagnum = -1 ;
  G__SteerPlotter_DictLN_SteerPlotter.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableSteerPlotter_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_TString);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_TObjArray);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_TArrayI);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_TArrayF);
   G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_BaseSteer);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SteerPlotter_DictLN_SteerPlotter),sizeof(SteerPlotter),-1,62720,"steering class for the SFrame Plotter",G__setup_memvarSteerPlotter,G__setup_memfuncSteerPlotter);
}
extern "C" void G__cpp_setupSteerPlotter_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupSteerPlotter_Dict()");
  G__set_cpp_environmentSteerPlotter_Dict();
  G__cpp_setup_tagtableSteerPlotter_Dict();

  G__cpp_setup_inheritanceSteerPlotter_Dict();

  G__cpp_setup_typetableSteerPlotter_Dict();

  G__cpp_setup_memvarSteerPlotter_Dict();

  G__cpp_setup_memfuncSteerPlotter_Dict();
  G__cpp_setup_globalSteerPlotter_Dict();
  G__cpp_setup_funcSteerPlotter_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncSteerPlotter_Dict();
  return;
}
class G__cpp_setup_initSteerPlotter_Dict {
  public:
    G__cpp_setup_initSteerPlotter_Dict() { G__add_setup_func("SteerPlotter_Dict",(G__incsetup)(&G__cpp_setupSteerPlotter_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initSteerPlotter_Dict() { G__remove_setup_func("SteerPlotter_Dict"); }
};
G__cpp_setup_initSteerPlotter_Dict G__cpp_setup_initializerSteerPlotter_Dict;

